default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: medical_center_rails_development


test:
  <<: *default
  database: medical_center_rails_test


production:
  primary: &primary_production
    <<: *default
    database: medical_center_rails_production
    username: medical_center_rails
    password: <%= ENV["MEDICAL_CENTER_RAILS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: medical_center_rails_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: medical_center_rails_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: medical_center_rails_production_cable
    migrations_paths: db/cable_migrate
